name: Build and Publish PR Docker Image

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Generate Git Tag
        id: vars
        run: echo "IMAGE_TAG=ghcr.io/shivamsnaik/postiz-app-pr:latest" >> $GITHUB_ENV

      - name: Build Docker image from Dockerfile.dev
        run: docker build -f Dockerfile.dev -t $IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: docker push $IMAGE_TAG
