name: Build and Publish PR Docker Image

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_dispatch:

permissions: write-all

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Generate Git Tag
        id: vars
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="1.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          run: echo "IMAGE_TAG=ghcr.io/shivamsnaik/postiz-app-pr:$NEW_TAG" >> $GITHUB_ENV

      - name: Build Docker image from Dockerfile.dev
        run: docker build -f Dockerfile.dev -t $IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: docker push $IMAGE_TAG
